---

nas:
  wunderhort:
    - backup
    - dokumente
    - home
    - stl
    - tabletop
    - passwoerter
    - medien
    - projekte
    - programming
    - research
    - k8s-nfs-storage-hdd
    - steam
    - scratch
  homedirs:
    - Downloads

datengruft:
  - passwords
