---
### Reminder how we want to structure this
#generic_package_names:
#  xyz:
#    Archlinux: xyz-arch
#  neovim:
#  abc:
#    Debian: abc-debian
#    Archlinux: abc-arch
#special_package_names:
#  Debian:
#    unique-apt:
#  Archlinux:
#    unique-arch:
###
special_package_blacklist:
  Debian: {}
  Archlinux:
    docker:
generic_package_blacklist:
  firefox-esr:
  # multilanguage input tool and environment
  uim:
  # another multilanguage tool
  ibus:
special_package_names:
  Debian:
    python-is-python3:
    cachefilesd:
    ntpsec:
    fonts-ebgaramond:
    fonts-ebgaramond-extra:
    fonts-ebgaramond-initials:
    fonts-ebgaramond-initials-extra:
    wcalc:
    temurin-23-jdk:
    vagrant:
    apt-file:
    apt-listchanges:
    alien:
    aptitude:
    wajig:
    nix-setup-systemd:
    google-cloud-cli:
    google-cloud-sdk-gke-gcloud-auth-plugin:
    genisoimage:
    oneko:
    qbrew:
    s4cmd:
    nextcloud-desktop-cmd:
    telnet:
    network-manager:
    wireguard:
    # dependencies for appimages
    libfuse2:
    fuse:
    # xfce4 stuff
    xfce4:
    xfce4-goodies:
    # kernel stuff
    firmware-misc-nonfree:
  Archlinux: {}
generic_package_names:
  # development
  git:
  zsh:
  tmux:
  ripgrep:
  shellcheck:
  # admin
  gpg:
    Archlinux: gnupg
  nmap:
  htop:
  btop:
  powertop:
  lshw:
  oathtool:
    Archlinux: oath-toolkit
  vault:
  ansible:
  ansible-lint:
  terraform:
  tofu:
    Archlinux: opentofu
  # media
  # storage
  nfs-common:
    Archlinux: nfs-utils
  # communication
  # system
  dex:
  # text
  jq:
  libreoffice:
  meld:
  texlive-full:
    Archlinux: texlive-meta
  texstudio:
  libimage-exiftool-perl:
    Archlinux: perl-image-exiftool
  pandoc:
  xsel:
  neovim:
  # development
  pipx:
    Archlinux: python-pipx
  maven:
  java-common:
    Archlinux: jdk-openjdk
  cmake:
  codium:
    Archlinux: code
  graphviz:
  astyle:
  hugo:
  yamllint:
  distrobox:
  plantuml:
  packer:
  qemu-utils:
    Debian: qemu-utils
    Archlinux: qemu-tools
  git-crypt:
  age:
  # databases
  mariadb-client:
    Archlinux: mariadb-clients
  postgresql-client-17:
    Archlinux: postgresql-libs
  # package management
  flatpak:
  nix-bin:
    Archlinux: nix
  # BEGIN docker stuff
  docker.io:
    Archlinux: podman-docker
  # END docker stuff
  # admin
  keepassxc:
  ipmitool:
  freeipmi:
  pwgen:
  remmina:
  # media
  simple-scan:
  okular:
  vlc:
  yt-dlp:
  ffmpeg:
  feh:
  chromium:
  ncmpcpp:
  mpd:
  cheese:
  flameshot:
  gimp:
  f3d:
  openscad:
  # entertainment
  wine:
  winetricks:
  # organisation
  gnucash:
  taskwarrior:
    Archlinux: taskwarrior-tui
  timewarrior:
    Archlinux: timew
  # files
  wget:
  curl:
  ncdu:
  7zip:
  pax:
  rsync:
  rclone:
  s3cmd:
  deluge:
  thunar:
  nextcloud-desktop:
    Archlinux: nextcloud-client
  syncthing:
  # communication
  thunderbird:
  # system
  # desktop stuff
  alacritty:
  # BEGIN awesome stuff
  awesome:
  # outputs battery charge
  acpi:
  # screen brightness
  brightnessctl:
  # manage screen layouts
  arandr:
  # END awesome stuff
  #- cinnamon
  # END DE stuff
  # networkstuff
  netcat-openbsd:
    Archlinux: openbsd-netcat
  whois:
  openconnect:
  wireguard-tools:
  # peripherals
  solaar:
  linux-headers-amd64:
    Archlinux: linux-headers

flatpaks:
#  - identifier: dev.zed.Zed
#    alias: zed
#    command: "flatpak run dev.zed.Zed $@"
  - identifier: com.github.qarmin.czkawka
    alias: czkawka
    command: "flatpak run com.github.qarmin.czkawka $@"
  - identifier: io.dbeaver.DBeaverCommunity
    alias: dbeaver
    command: "flatpak run io.dbeaver.DBeaverCommunity $@"
  #- identifier: com.vscodium.codium
  #  alias: codium
  #  command: "flatpak run com.vscodium.codium $@"
  #- identifier: org.gnome.Evince
  #  alias: evince
  #  command: "flatpak run org.gnome.Evince $@"
  - identifier: org.telegram.desktop
    alias: telegram
    command: "flatpak run org.telegram.desktop $@"
  - identifier: com.discordapp.Discord
    alias: discord
    command: "flatpak run com.discordapp.Discord $@"
  - identifier: info.portfolio_performance.PortfolioPerformance
    alias: portfolio
    command: "flatpak run info.portfolio_performance.PortfolioPerformance $@"
  - identifier: com.github.tchx84.Flatseal
    alias: flatseal
    command: "flatpak run com.github.tchx84.Flatseal $@"
  - identifier: com.github.Matoking.protontricks
    alias: protontricks
    command: flatpak run com.github.Matoking.protontricks

homebrew_taps:
  - quarkusio/tap
  - minio/stable

homebrew_packages:
  - zig
  - rustup
  - golang
  - delve
  - quarkusio/tap/quarkus
  - yj
  # this is the (nicer) mike farah version
  # https://github.com/mikefarah/yq
  # the one in the package sources is the slightly less nice variant
  - yq
  # https://grafana.com/docs/mimir/latest/manage/tools/mimirtool/
  - mimirtool
  - micromamba
  - pixi
  - ruff
  - npm
  - yarn
  - nvm
  - hadolint
  - liquibase
  - oras
  - mongosh
  - minio/stable/mc
  - sops
  - dive
  - grpcurl
  - bufbuild/buf/buf
  # kubernetes related
  - argocd
  - cilium-cli
  - clusterctl
  - istioctl
  - k9s
  - kubeconform
  - kubectl
  - kubent
  - kustomize
  - kind
  - kubescape
  - openbao
  - popeye
  - helm
  - helmfile
  - minikube
  - stern
